<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <link rel="stylesheet" href="globals.css" />
    <link rel="stylesheet" href="styleguide.css" />
    <link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="main">
    <div class="header">
        <div class="container">
            <div class="div-wrapper">
                <button class="button">
                    <div class="div"><div class="text-wrapper">menu</div></div>
                </button>
            </div>
            <div class="container-2"><p class="text-wrapper-2">NHÀ THUỐC Chi nhánh DEMO</p></div>
            <div class="div-wrapper-2">
                <button class="button">
                    <div class="div"><div class="text-wrapper">arrow_drop_down</div></div>
                </button>
            </div>
        </div>
        <div class="container">
            <div class="container">
                <div class="container-2"><div class="text-wrapper-3">thermostat</div></div>
                <div class="div-wrapper-2"><div class="text-wrapper-4">0°C</div></div>
                <div class="margin"><div class="text-wrapper-5">cloud</div></div>
                <div class="div-wrapper-2"><div class="text-wrapper-4">000</div></div>
            </div>
            <div class="div-wrapper-3">
                <div class="container">
                    <div class="container-2"><div class="text-wrapper-6">calendar_today</div></div>
                    <div class="div-wrapper-2"><div class="text-wrapper-4">01/01/2200</div></div>
                </div>
            </div>
            <div class="div-wrapper-3">
                <button class="button">
                    <div class="div"><div class="text-wrapper">play_arrow</div></div>
                </button>
            </div>
            <div class="div-wrapper-3">
                <div class="container">
                    <div class="container-2"><div class="text-wrapper-7">lightbulb</div></div>
                    <div class="div-wrapper-2"><div class="text-wrapper-4">Tiện ích</div></div>
                </div>
            </div>
            <div class="div-wrapper-3">
                <div class="container">
                    <div class="container-2"><div class="text-wrapper-7">account_circle</div></div>
                    <div class="div-wrapper-2"><div class="text-wrapper-4">hni8686_admin</div></div>
                    <button class="container-wrapper">
                        <div class="div"><div class="text-wrapper">arrow_drop_down</div></div>
                    </button>
                </div>
            </div>
        </div>
    </div>
    <div class="background">
        <div class="background-shadow">
            <div class="horizontal-border">
                <div class="container-3">
                    <div class="input">
                        <div class="container-4"><div class="text-wrapper-8">Tìm kiếm hàng hóa</div></div>
                    </div>
                    <div class="text-wrapper-9">search</div>
                </div>
                <div class="margin-2">
                    <div class="container-5">
                        <div class="h-a-n-wrapper">
                            <div class="h-a-n">HÓA<br />ĐƠN 1</div>
                        </div>
                        <div class="background-2"></div>
                    </div>
                </div>
            </div>
            <div class="table-wrapper">
                <div class="div-2">
                    <div class="row-wrapper">
                        <div class="row">
                            <div class="cell"><div class="text-wrapper-10">#</div></div>
                            <div class="div-3"><div class="text-wrapper-10">Tên hàng</div></div>
                            <div class="cell-2"><div class="text-wrapper-10">Đơn vị tính</div></div>
                            <div class="cell-3"><div class="text-wrapper-10">Số lượng</div></div>
                            <div class="cell-4"><div class="text-wrapper-10">Giá bán</div></div>
                            <div class="cell-5"><div class="text-wrapper-10">Thành tiền</div></div>
                        </div>
                    </div>
                    <div class="div-2">
                        <div class="row-2">
                            <div class="data"><div class="text-wrapper-11">1</div></div>
                            <div class="div-3">
                                <div class="div-2"><div class="text-wrapper-12">Clopivir</div></div>
                                <div class="div-2">
                                    <p class="text-wrapper-13">Hộp 3 vỉ x 10 viên; 1 vỉ x 14 viên nén bao phim</p>
                                </div>
                                <div class="div-2">
                                    <p class="text-wrapper-13">Số lô: 200402 - HSD: 22/04/2023 - Ngày nhập: 22/04/2021</p>
                                </div>
                                <div class="div-2"><div class="text-wrapper-14">Liều dùng</div></div>
                            </div>
                            <div class="data-2">
                                <div class="div-2"><div class="text-wrapper-15">Viên</div></div>
                                <div class="div-2"><div class="text-wrapper-13">Tồn: 1,069</div></div>
                            </div>
                            <div class="data-3"><div class="text-wrapper-11">2</div></div>
                            <div class="data-4"><div class="text-wrapper-11">1,000.00</div></div>
                            <div class="data-5">
                                <div class="div-2"><div class="text-wrapper-12">2,000.00</div></div>
                                <div class="div-2"><div class="text-wrapper-13">VAT: 0.00 (0%)</div></div>
                            </div>
                            <button class="button-wrapper">
                                <button class="button-2">
                                    <div class="div"><div class="text-wrapper-16">delete</div></div>
                                </button>
                            </button>
                        </div>
                        <div class="row-3">
                            <div class="data-6"><div class="text-wrapper-11">2</div></div>
                            <div class="div-3">
                                <div class="div-2"><div class="text-wrapper-12">Panactol - Extra</div></div>
                                <div class="div-2"><p class="text-wrapper-13">Hộp 10 vỉ x 10 viên</p></div>
                                <div class="div-2">
                                    <p class="text-wrapper-13">Số lô: 123 - HSD: 12/02/2024 - sáng 1 lần, trưa 1 lần, chiều 1 lần</p>
                                </div>
                            </div>
                            <div class="data-7">
                                <div class="div-2"><div class="text-wrapper-15">Viên</div></div>
                                <div class="div-2"><div class="text-wrapper-13">Tồn: 991</div></div>
                            </div>
                            <div class="data-8"><div class="text-wrapper-11">3</div></div>
                            <div class="data-9"><div class="text-wrapper-11">1,000.00</div></div>
                            <div class="data-10">
                                <div class="div-2"><div class="text-wrapper-12">3,000.00</div></div>
                                <div class="div-2"><div class="text-wrapper-13">VAT: 0.00 (0%)</div></div>
                            </div>
                            <button class="data-11">
                                <button class="button-2">
                                    <div class="div"><div class="text-wrapper-16">delete</div></div>
                                </button>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="background-shadow-wrapper">
            <div class="background-shadow-2">
                <div class="div-wrapper-4">
                    <div class="div-2"><div class="text-wrapper-17">Thanh toán</div></div>
                </div>
                <div class="div-wrapper-4">
                    <div class="container-6">
                        <div class="container">
                            <div class="div-wrapper"><div class="text-wrapper-18">account_circle</div></div>
                            <div class="container-2"><div class="text-wrapper-4">hni8686_admin</div></div>
                        </div>
                        <div class="container-2"><div class="text-wrapper-19">10/08/2022 09:55</div></div>
                    </div>
                </div>
                <div class="div-wrapper-4">
                    <div class="container-7">
                        <div class="div-2"><div class="text-wrapper-20">Tên khách hàng</div></div>
                        <div class="div-2">
                            <div class="input-2">
                                <div class="container-8"><div class="text-wrapper-21">Trần Văn A</div></div>
                            </div>
                            <button class="button-3">
                                <div class="div"><div class="text-wrapper-16">close</div></div>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="div-wrapper-4">
                    <div class="container-9">
                        <div class="container-10">
                            <div class="container-2"><div class="text-wrapper-4">Tổng tiền hàng</div></div>
                            <div class="container-2"><div class="text-wrapper-2">5,000.00</div></div>
                        </div>
                        <div class="container-6">
                            <div class="container-2"><div class="text-wrapper-4">Khách cần trả</div></div>
                            <div class="container-2"><div class="text-wrapper-22">5,000.00</div></div>
                        </div>
                        <div class="horizontal-border-2">
                            <div class="container-2"><div class="text-wrapper-23">Khách thanh toán (F8)</div></div>
                            <div class="input-3">
                                <div class="container-11"><div class="text-wrapper-24">5,000</div></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="div-wrapper-4">
                    <div class="container-7">
                        <div class="div-2"><div class="text-wrapper-20">Phương thức thanh toán</div></div>
                        <div class="options">
                            <div class="image-fill">
                                <div class="image"><img class="vector" src="img/vector.svg" /></div>
                            </div>
                            <div class="container-12"><div class="text-wrapper-25">Tiền mặt</div></div>
                        </div>
                    </div>
                </div>
                <div class="div-wrapper-4">
                    <div class="container-6">
                        <div class="container-2"><div class="text-wrapper-4">Tiền thừa trả khách</div></div>
                        <div class="container-2"><div class="text-wrapper-2">0.00</div></div>
                    </div>
                </div>
                <div class="margin-3">
                    <div class="container-13">
                        <div class="div-2"><div class="text-wrapper-20">Ghi chú</div></div>
                        <div class="textarea"></div>
                    </div>
                </div>
                <div class="container-14">
                    <button class="button-4"><div class="text-wrapper-26">THANH TOÁN (F9)</div></button>
                    <button class="button-5">
                        <div class="div"><div class="text-wrapper-27">comment</div></div>
                    </button>
                    <button class="button-6">
                        <div class="div"><div class="text-wrapper-27">print</div></div>
                    </button>
                    <button class="button-7">
                        <div class="div"><div class="text-wrapper-27">settings</div></div>
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>
