<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta charset="utf-8" />
    <link rel="stylesheet" href="globals.css" />
    <link rel="stylesheet" href="styleguide.css" />
    <link rel="stylesheet" href="style.css" />
</head>
<body>
<div class="frame">
    <div class="container">
        <div class="aside">
            <div class="horizontal-border">
                <div class="div-wrapper"><div class="text-wrapper">QUẢN LÝ NHÀ THUỐC</div></div>
            </div>
            <div class="nav-margin">
                <div class="nav">
                    <div class="div">
                        <div class="div-2">
                            <div class="div-wrapper"><div class="text-wrapper-2">dashboard</div></div>
                            <div class="margin"><div class="text-wrapper-3">Tổng quan</div></div>
                        </div>
                        <div class="div-2">
                            <div class="div-wrapper"><div class="text-wrapper-2">shopping_cart</div></div>
                            <div class="margin"><div class="text-wrapper-3">Bán hàng</div></div>
                        </div>
                        <div class="item">
                            <div class="div-wrapper"><div class="text-wrapper-4">receipt_long</div></div>
                            <div class="margin"><div class="text-wrapper-5">Quản lý hóa đơn</div></div>
                        </div>
                        <div class="div-2">
                            <div class="div-wrapper"><div class="text-wrapper-2">bar_chart</div></div>
                            <div class="margin"><div class="text-wrapper-6">Báo cáo</div></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="button-wrapper">
                <button class="button">
                    <div class="container-2"><div class="text-wrapper-7">power_settings_new</div></div>
                </button>
            </div>
        </div>
        <div class="container-3">
            <div class="header">
                <div class="div-3">
                    <div class="div-wrapper"><div class="text-wrapper-2">menu</div></div>
                    <div class="margin-2">
                        <div class="div-3">
                            <div class="container-2"><p class="p">NHÀ THUỐC Chi Nhánh DEMO</p></div>
                            <div class="div-wrapper-2">
                                <div class="container-2"><div class="text-wrapper-8">arrow_drop_down</div></div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="div-3">
                    <div class="div-3">
                        <div class="div-wrapper"><div class="text-wrapper-9">thermostat</div></div>
                        <div class="div-wrapper-2"><div class="text-wrapper-10">0°C</div></div>
                        <div class="div-wrapper-2"><div class="text-wrapper-11">water_drop</div></div>
                        <div class="div-wrapper-2"><div class="text-wrapper-12">0%</div></div>
                    </div>
                    <div class="margin-2">
                        <div class="background-border">
                            <div class="div-wrapper"><div class="text-wrapper-13">calendar_today</div></div>
                            <div class="div-wrapper-2"><div class="text-wrapper-14">01/01/2200</div></div>
                            <div class="div-wrapper-2"><div class="text-wrapper-13">arrow_drop_down</div></div>
                        </div>
                    </div>
                    <div class="margin-2"><div class="text-wrapper-2">extension</div></div>
                    <div class="margin-2">
                        <div class="div-3">
                            <div class="div-wrapper"><div class="text-wrapper-2">person</div></div>
                            <div class="div-wrapper-2"><div class="text-wrapper-15">hnh8686_admin</div></div>
                        </div>
                    </div>
                    <div class="background-wrapper"><div class="background"></div></div>
                </div>
            </div>
            <div class="main">
                <div class="container-4">
                    <div class="div-3">
                        <div class="margin-3"><div class="text-wrapper-2">menu</div></div>
                        <div class="text-wrapper-16">QUẢN LÝ HÓA ĐƠN</div>
                    </div>
                    <div class="container-5">
                        <div class="button-2">
                            <div class="container-2"><div class="text-wrapper-7">add</div></div>
                            <div class="div-wrapper-2">
                                <div class="container-2"><p class="text-wrapper-17">THÊM MỚI TỪ FILE EXCEL</p></div>
                            </div>
                        </div>
                        <div class="div-wrapper-2">
                            <div class="button-3">
                                <div class="container-2"><div class="text-wrapper-7">file_download</div></div>
                                <div class="div-wrapper-2">
                                    <div class="container-2"><div class="text-wrapper-18">XUẤT FILE EXCEL</div></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="background-shadow">
                    <div class="container-6">
                        <div class="container-7">
                            <div class="div"><div class="text-wrapper-19">Từ ngày</div></div>
                            <div class="div">
                                <div class="input">
                                    <div class="container-8"><div class="text-wrapper-20">01/08/2022</div></div>
                                </div>
                                <div class="container-9"><div class="text-wrapper-21">calendar_today</div></div>
                            </div>
                        </div>
                        <div class="container-10">
                            <div class="div"><div class="text-wrapper-22">Tới ngày</div></div>
                            <div class="div">
                                <div class="input">
                                    <div class="container-8"><div class="text-wrapper-20">10/08/2022</div></div>
                                </div>
                                <div class="container-9"><div class="text-wrapper-21">calendar_today</div></div>
                            </div>
                        </div>
                        <div class="container-11">
                            <div class="div"><p class="text-wrapper-23">Loại thời gian tìm kiếm</p></div>
                            <div class="options">
                                <div class="image-fill">
                                    <div class="image"><img class="vector" src="img/vector-2.svg" /></div>
                                </div>
                                <div class="container-12"><div class="text-wrapper-24">Ngày bán</div></div>
                            </div>
                        </div>
                        <div class="container-13">
                            <div class="div"><div class="text-wrapper-25">Trạng thái</div></div>
                            <div class="options">
                                <div class="image-fill">
                                    <div class="image"><img class="vector" src="img/vector-3.svg" /></div>
                                </div>
                                <div class="container-12"><div class="text-wrapper-26">Tất cả</div></div>
                            </div>
                        </div>
                        <div class="container-14">
                            <div class="div"><div class="text-wrapper-25">Trạng thái liên thông</div></div>
                            <div class="options">
                                <div class="image-fill">
                                    <div class="image"><img class="vector" src="img/vector.svg" /></div>
                                </div>
                                <div class="container-12"><div class="text-wrapper-26">Tất cả</div></div>
                            </div>
                        </div>
                        <div class="container-15">
                            <div class="div"><div class="text-wrapper-27">Hoá đơn</div></div>
                            <div class="options">
                                <div class="image-fill">
                                    <div class="image"><img class="vector" src="img/image.svg" /></div>
                                </div>
                                <div class="container-12"><div class="text-wrapper-26">Tất cả</div></div>
                            </div>
                        </div>
                        <div class="container-16">
                            <div class="div"><div class="text-wrapper-25">Phương thức thanh toán</div></div>
                            <div class="options">
                                <div class="image-fill">
                                    <div class="image"><img class="vector" src="img/vector-4.svg" /></div>
                                </div>
                                <div class="container-12"><div class="text-wrapper-26">Tất cả</div></div>
                            </div>
                        </div>
                        <div class="container-17">
                            <div class="div"><p class="text-wrapper-28">Tìm kiếm theo hàng hoá</p></div>
                            <div class="container-wrapper">
                                <div class="container-18"><p class="text-wrapper-29">Nhập mã hoặc tên hàng hóa, Ân Enter</p></div>
                            </div>
                        </div>
                        <div class="container-19">
                            <div class="div"><p class="text-wrapper-28">Từ khóa tìm kiếm (F3)</p></div>
                            <div class="container-20">
                                <div class="input-2">
                                    <div class="container-21"><p class="text-wrapper-30">Tìm kiếm theo mã hoá đơn,</p></div>
                                </div>
                                <div class="button-4">
                                    <div class="container-2"><div class="text-wrapper-7">search</div></div>
                                    <div class="div-wrapper-2">
                                        <div class="container-2"><div class="text-wrapper-31">TÌM KIẾM</div></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="background-shadow-2">
                    <div class="heading-wrapper">
                        <div class="div"><p class="text-wrapper-32">Danh sách hóa đơn (12 Hoá đơn)</p></div>
                    </div>
                    <div class="table">
                        <div class="row-wrapper">
                            <div class="row">
                                <div class="cell"><div class="text-wrapper-33">#</div></div>
                                <div class="div-4"><div class="text-wrapper-34">Mã hóa đơn</div></div>
                                <div class="cell-2"><div class="text-wrapper-35">Khách hàng</div></div>
                                <div class="div-5"><div class="text-wrapper-35">Ngày giờ bán hàng</div></div>
                                <div class="cell-3"><div class="text-wrapper-36">Tổng tiền</div></div>
                                <div class="cell-4"><div class="text-wrapper-37">Thanh toán</div></div>
                                <div class="cell-5"><div class="text-wrapper-38">Ghi chú</div></div>
                                <div class="cell-6"><div class="text-wrapper-39">Trạng thái</div></div>
                            </div>
                        </div>
                        <div class="div">
                            <div class="row-2">
                                <div class="data"><div class="text-wrapper-40">1</div></div>
                                <div class="div-4">
                                    <div class="text-wrapper-41">HD0000918</div>
                                    <div class="text-wrapper-42">Không bán theo đơn</div>
                                </div>
                                <div class="data-2"><div class="text-wrapper-43">Trần Văn A</div></div>
                                <div class="div-5">
                                    <div class="text-wrapper-44">10/08/2022 09:59</div>
                                    <div class="text-wrapper-45">Ngày tạo: 10/08/2022 09:59</div>
                                </div>
                                <div class="data-3"><div class="text-wrapper-46">5,000.00</div></div>
                                <div class="data-4"><div class="text-wrapper-46">5,000.00</div></div>
                                <div class="data-5">
                                    <div class="margin-4"><div class="text-wrapper-47">check_circle</div></div>
                                    <div class="text-wrapper-48">Hoàn Thành</div>
                                </div>
                                <div class="data-6">
                                    <div class="button-5">
                                        <div class="container-2"><div class="text-wrapper-49">THAO TÁC</div></div>
                                        <div class="margin-5">
                                            <div class="container-2"><div class="text-wrapper-50">arrow_drop_down</div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-3">
                                <div class="data-7"><div class="text-wrapper-40">2</div></div>
                                <div class="data-8">
                                    <div class="text-wrapper-51">HD0000917</div>
                                    <div class="text-wrapper-42">Không bán theo đơn</div>
                                </div>
                                <div class="data-9"><div class="text-wrapper-43">Trần Văn A</div></div>
                                <div class="data-10">
                                    <div class="text-wrapper-44">10/08/2022 09:55</div>
                                    <div class="text-wrapper-45">Ngày tạo: 10/08/2022 09:54</div>
                                </div>
                                <div class="data-11"><div class="text-wrapper-52">315,000.00</div></div>
                                <div class="data-12"><div class="text-wrapper-52">315,000.00</div></div>
                                <div class="data-5">
                                    <div class="margin-4"><div class="text-wrapper-47">check_circle</div></div>
                                    <div class="text-wrapper-48">Hoàn Thành</div>
                                </div>
                                <div class="data-13">
                                    <div class="button-5">
                                        <div class="container-2"><div class="text-wrapper-49">THAO TÁC</div></div>
                                        <div class="margin-5">
                                            <div class="container-2"><div class="text-wrapper-50">arrow_drop_down</div></div>
                                        </div>
                                    </div>
                                    <div class="background-shadow-3">
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-53">visibility</div></div>
                                            <div class="text-wrapper-54">Chi tiết phiếu</div>
                                        </div>
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-53">print</div></div>
                                            <div class="text-wrapper-55">In phiếu</div>
                                        </div>
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-53">print</div></div>
                                            <div class="text-wrapper-55">In liều dùng</div>
                                        </div>
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-56">close</div></div>
                                            <div class="text-wrapper-57">Huỷ hoá đơn</div>
                                        </div>
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-53">assignment_return</div></div>
                                            <div class="text-wrapper-41">Tạo phiếu khách trả</div>
                                        </div>
                                        <div class="div-2">
                                            <div class="margin-3"><div class="text-wrapper-53">link</div></div>
                                            <div class="text-wrapper-41">Liên thông phiếu</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-4">
                                <div class="data-7"><div class="text-wrapper-40">3</div></div>
                                <div class="data-8">
                                    <div class="text-wrapper-41">HD0000916</div>
                                    <div class="text-wrapper-42">Không bán theo đơn</div>
                                </div>
                                <div class="data-9"><div class="text-wrapper-43">Trần Văn A</div></div>
                                <div class="data-10">
                                    <div class="text-wrapper-44">10/08/2022 09:47</div>
                                    <div class="text-wrapper-45">Ngày tạo: 10/08/2022 09:47</div>
                                </div>
                                <div class="data-11"><div class="text-wrapper-58">132,000.00</div></div>
                                <div class="data-12"><div class="text-wrapper-58">132,000.00</div></div>
                                <div class="data-5">
                                    <div class="margin-4"><div class="text-wrapper-47">check_circle</div></div>
                                    <div class="text-wrapper-48">Hoàn Thành</div>
                                </div>
                                <div class="data-6">
                                    <div class="button-5">
                                        <div class="container-2"><div class="text-wrapper-49">THAO TÁC</div></div>
                                        <div class="margin-5">
                                            <div class="container-2"><div class="text-wrapper-50">arrow_drop_down</div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row-4">
                                <div class="data-14"><div class="text-wrapper-40">4</div></div>
                                <div class="div-4">
                                    <div class="text-wrapper-51">HD0000915</div>
                                    <div class="text-wrapper-42">Không bán theo đơn</div>
                                </div>
                                <div class="data-15"><div class="text-wrapper-59">Lý Chi Cao</div></div>
                                <div class="div-5">
                                    <div class="text-wrapper-44">10/08/2022 09:25</div>
                                    <div class="text-wrapper-45">Ngày tạo: 10/08/2022 09:25</div>
                                </div>
                                <div class="data-16"><div class="text-wrapper-52">100,000.00</div></div>
                                <div class="data-17"><div class="text-wrapper-52">100,000.00</div></div>
                                <div class="data-5">
                                    <div class="margin-4"><div class="text-wrapper-47">check_circle</div></div>
                                    <div class="text-wrapper-48">Hoàn Thành</div>
                                </div>
                                <div class="data-6">
                                    <div class="button-5">
                                        <div class="container-2"><div class="text-wrapper-49">THAO TÁC</div></div>
                                        <div class="margin-5">
                                            <div class="container-2"><div class="text-wrapper-50">arrow_drop_down</div></div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>