

@template.layouts.warehouse(
headContent = @`
    <title>Quản Lý Kho Tổng</title>
    <link rel="stylesheet" href="/assets/css/warehouse/warehouse_manage.css">
`,
content = @`
    <div class="container">
        <div class="main-frame">
            <div class="background-image"></div>
        </div>
    </div>
`,
pageScript = @`
    <script src="/assets/js/warehouse/warehouse_manage.js" defer></script>
`
)
